# Question 1

In [34]:
import numpy as np

In [35]:
arr=np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Question 2

In [50]:
l1=[]
l2=[]
for i in range(5):
    l1.append(input())
for j in range(5):
    l2.append(input())
print(l1)
print(l2)

1
4
2
3
5
7
6
2
8
3
['1', '4', '2', '3', '5']
['7', '6', '2', '8', '3']


In [51]:
np.array(l1)
np.array(l2)
a=(l1+l2)
print(a)

['1', '4', '2', '3', '5', '7', '6', '2', '8', '3']


In [52]:
import numpy as np
print(np.sort(a))

['1' '2' '2' '3' '3' '4' '5' '6' '7' '8']


# Question 3

In [58]:
a1=np.array([[2,2,2],[3,3,3],[4,4,4]])
print(a1.shape)

(3, 3)


In [60]:
print(np.size(a1))

9


# Question 4

In [77]:
array1=np.array([1,2,3,4,5,6,7,8,9,10])
print(array1.reshape(2,5))
print(array1[np.newaxis:np.newaxis:np.newaxis])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


# Question 5

In [81]:
import numpy as np
a1=np.array([1,2,3,4,5])
a2=np.array([3,4,5,6,7])
print(np.hstack((a1,a2)))
print(np.vstack((a1,a2)))

[1 2 3 4 5 3 4 5 6 7]
[[1 2 3 4 5]
 [3 4 5 6 7]]


# Question 6

In [82]:
arr=np.array([1,2,3,1,4,52,6,7,25,4,8,9,1,6,10,3,5,6,8,9,4,9])
print(np.unique(arr))

[ 1  2  3  4  5  6  7  8  9 10 25 52]


In [90]:
uniqueValues, occurCount = np.unique(arr, return_counts=True)
print(uniqueValues)
print(occurCount)

[ 1  2  3  4  5  6  7  8  9 10 25 52]
[3 1 2 3 1 3 1 2 3 1 1 1]
